# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 12:07
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duet_admin', '0001_initial'),
        ('duet_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, populate_from='name', unique_with=('id',))),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tax_id_number', models.CharField(max_length=20, null=True, verbose_name='Tax ID')),
                ('account_number', models.CharField(max_length=20, null=True, verbose_name='Account Number')),
                ('joining_date', models.DateField(null=True, verbose_name='Joining Date')),
                ('category', models.CharField(choices=[('', '----'), ('t', 'Teacher'), ('o', 'Officer'), ('s', 'Stuff')], default='t', max_length=1, verbose_name='Category')),
                ('allowance_deductions', models.ManyToManyField(through='duet_account.EmployeeAllowanceDeduction', to='duet_account.AllowanceDeduction')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Designation', verbose_name='Designation')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='duet_account.Grade', verbose_name='Grade')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('duet_admin.user',),
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('resigning_date', models.DateField(null=True)),
                ('is_active', models.BooleanField()),
                ('comment', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Designation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
