# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 06:41
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhistory',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='employee',
        ),
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='WorkHistory',
        ),
    ]
