# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20161009_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified At'),
        ),
    ]
