# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 21:49
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20161009_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, populate_from='name', unique=True),
        ),
    ]
