# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 14:21
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duet_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, populate_from='name', unique_with=('id',)),
        ),
    ]
