# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 06:41
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duet_admin', '0002_auto_20161008_2021'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
