# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duet_admin', '0004_auto_20161009_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('value', models.IntegerField(verbose_name='Value')),
            ],
        ),
    ]
