# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 12:07
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='Code')),
                ('category', models.CharField(choices=[('', '----'), ('p', 'Pay'), ('a', 'Allowance'), ('d', 'Deduction')], max_length=2, verbose_name='Type')),
                ('is_percentage', models.BooleanField(verbose_name='Percentage')),
                ('is_applicable', models.BooleanField(verbose_name='Applicable')),
                ('payment_type', models.CharField(choices=[('y', 'Yearly'), ('hy', 'Half Yearly'), ('m', 'Monthly'), ('o', 'One Time')], default='m', max_length=2, verbose_name='Payment Type')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, populate_from='name', unique_with=('id',))),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AllowanceDeductionEmployeeClassValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAllowanceDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=0, verbose_name='Value')),
                ('is_percentage', models.BooleanField(verbose_name='Percentage')),
                ('is_applicable', models.BooleanField(verbose_name='Applicable')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'ordering': ['allowance_deduction__order'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank='True', null=True, verbose_name='Description')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, populate_from='name', unique_with=('id',))),
            ],
        ),
        migrations.CreateModel(
            name='GPFAdvance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('no_of_installments', models.IntegerField(verbose_name='No of Installments')),
                ('monthly_payment', models.FloatField(verbose_name='Monthly Payment')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Closing Date')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
            ],
        ),
        migrations.CreateModel(
            name='GPFAdvanceInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.IntegerField(verbose_name='Install No.')),
                ('deduction', models.FloatField(verbose_name='Deduction')),
                ('interest', models.FloatField(default=0, verbose_name='Interest')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'ordering': ['installment_no'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_no', models.IntegerField(verbose_name='Grade')),
                ('description', models.TextField(blank='True', null=True, verbose_name='Description')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, populate_from='grade_no', unique_with=('id',))),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyLogForGPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction', models.FloatField(default=0, verbose_name='Deduction')),
                ('interest', models.FloatField(default=0, verbose_name='Interest')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'ordering': ['salary_sheet__date'],
            },
        ),
        migrations.CreateModel(
            name='ProvidentFundProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_interest', models.BooleanField(default=True, verbose_name='Interest Taken')),
                ('percentage', models.IntegerField(default=0, verbose_name='Percentage')),
            ],
        ),
        migrations.CreateModel(
            name='SalarySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Month Ending')),
                ('is_freezed', models.BooleanField(default=False, verbose_name='Freezed')),
                ('is_withdrawn', models.BooleanField(default=True, verbose_name='Withdrawn')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='SalarySheetDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('allowance_deduction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duet_account.AllowanceDeduction')),
                ('salary_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duet_account.SalarySheet')),
            ],
            options={
                'ordering': ['allowance_deduction__order'],
            },
        ),
        migrations.CreateModel(
            name='YearlyLogForGPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Year Ending')),
                ('net_deduction', models.FloatField(verbose_name='Net Deduction')),
                ('net_interest', models.FloatField(verbose_name='Net Interest')),
                ('total_credit', models.FloatField(verbose_name='Total')),
                ('is_freezed', models.BooleanField(default=False, verbose_name='Freezed')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Modified At')),
                ('provident_fund_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duet_account.ProvidentFundProfile', verbose_name='Employee')),
            ],
        ),
        migrations.AddField(
            model_name='salarysheet',
            name='allowance_deductions',
            field=models.ManyToManyField(through='duet_account.SalarySheetDetails', to='duet_account.AllowanceDeduction'),
        ),
    ]
