# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('duet_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarysheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='providentfundprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='monthlylogforgpf',
            name='provident_fund_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duet_account.ProvidentFundProfile', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='monthlylogforgpf',
            name='salary_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duet_account.SalarySheet', verbose_name='Salary Sheet'),
        ),
        migrations.AddField(
            model_name='grade',
            name='employee_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duet_account.EmployeeClass', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='gpfadvanceinstallment',
            name='gpf_advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duet_account.GPFAdvance', verbose_name='GPF Advance'),
        ),
        migrations.AddField(
            model_name='gpfadvanceinstallment',
            name='salary_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duet_account.SalarySheet', verbose_name='Salary Sheet'),
        ),
        migrations.AddField(
            model_name='gpfadvance',
            name='provident_fund_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duet_account.ProvidentFundProfile', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeeallowancededuction',
            name='allowance_deduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duet_account.AllowanceDeduction', verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='employeeallowancededuction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='allowancedeductionemployeeclassvalue',
            name='allowance_deduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duet_account.AllowanceDeduction'),
        ),
        migrations.AddField(
            model_name='allowancedeductionemployeeclassvalue',
            name='employee_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duet_account.EmployeeClass'),
        ),
        migrations.AddField(
            model_name='allowancededuction',
            name='value',
            field=models.ManyToManyField(through='duet_account.AllowanceDeductionEmployeeClassValue', to='duet_account.EmployeeClass'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeallowancededuction',
            unique_together=set([('employee', 'allowance_deduction')]),
        ),
        migrations.AlterUniqueTogether(
            name='allowancedeductionemployeeclassvalue',
            unique_together=set([('employee_class', 'allowance_deduction')]),
        ),
    ]
