# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duet_account', '0002_auto_20161008_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeallowancededuction',
            name='is_percentage',
        ),
        migrations.RemoveField(
            model_name='salarysheet',
            name='is_freezed',
        ),
    ]
