# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duet_account', '0003_auto_20161008_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarysheet',
            name='is_freezed',
            field=models.BooleanField(default=False, verbose_name='Freezed'),
        ),
    ]
