# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duet_account', '0006_auto_20161128_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancedeductionemployeeclassvalue',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeeallowancededuction',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='gpfadvance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='gpfadvance',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Monthly Payment'),
        ),
        migrations.AlterField(
            model_name='gpfadvanceinstallment',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deduction'),
        ),
        migrations.AlterField(
            model_name='gpfadvanceinstallment',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Interest'),
        ),
        migrations.AlterField(
            model_name='monthlylogforgpf',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deduction'),
        ),
        migrations.AlterField(
            model_name='monthlylogforgpf',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Interest'),
        ),
        migrations.AlterField(
            model_name='salarysheetdetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='yearlylogforgpf',
            name='net_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Deduction'),
        ),
        migrations.AlterField(
            model_name='yearlylogforgpf',
            name='net_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Interest'),
        ),
        migrations.AlterField(
            model_name='yearlylogforgpf',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
    ]
