# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20161009_1306'),
        ('duet_account', '0007_auto_20161213_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount')),
                ('no_of_installments', models.IntegerField(verbose_name='No of Installments')),
                ('monthly_payment', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Monthly Payment')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Closing Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee', verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='HomeLoanInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.IntegerField(verbose_name='Install No.')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deduction')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('home_loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duet_account.HomeLoan', verbose_name='Home Loan')),
                ('salary_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duet_account.SalarySheet', verbose_name='Salary Sheet')),
            ],
            options={
                'ordering': ['installment_no'],
            },
        ),
    ]
