# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duet_account', '0008_homeloan_homeloaninstallment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpfadvanceinstallment',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='homeloaninstallment',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='monthlylogforgpf',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='gpfadvance',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
        migrations.AddField(
            model_name='homeloan',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
    ]
