# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duet_account', '0010_auto_20161214_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancededuction',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gpfadvance',
            name='is_freezed',
            field=models.BooleanField(default=False, verbose_name='Freezed'),
        ),
        migrations.AlterField(
            model_name='homeloan',
            name='is_freezed',
            field=models.BooleanField(default=False, verbose_name='Freezed'),
        ),
    ]
