# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duet_account', '0011_auto_20161214_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowancededuction',
            name='modified_by',
        ),
    ]
