# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 21:49
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duet_account', '0013_auto_20161230_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Activated Date')),
                ('is_active', models.BooleanField(verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='allowancededuction',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='employeeclass',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, populate_from='grade_no', unique=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='salary_scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='duet_account.SalaryScale'),
        ),
    ]
