# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duet_account', '0015_auto_20161230_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='salary_scale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='duet_account.SalaryScale'),
            preserve_default=False,
        ),
    ]
